theme: jekyll-theme-leap-day
title: [New Client Information]
description: [Please Completed Prior To First Appointment.]
show_downloads: [False]
google_analytics: [Your Google Analytics tracking ID]
github:
  url: http://example.com/download.zip
  

